/* One Scroll Bible · cinematic reader. No framework, canvas loop, or scroll hijacking. */
(function(global){
  'use strict';
  const rows = [
    ['creation','처음에는, 함께였다.','하나님은 좋은 세상을 만드시고 사람을 그 안에 두셨습니다. 사람은 하나님과, 서로와, 세상과 조화롭게 살아가도록 지음받았습니다.','그런데 사람은 하나님 없이도 잘 살 수 있다고 생각했습니다.','In the beginning, together.','God made a good world and placed people in it. They were made to live in harmony with God, with one another, and with the world.','But people began to believe they could live well without God.'],
    ['fall','집으로 가는 길을 잃다.','사람은 하나님을 불신하고 등을 돌렸습니다. 죄와 죽음이 들어오고 관계는 깨졌습니다. 그러나 하나님은 악을 이길 구원자를 약속하셨습니다.','깨어진 세상을 되돌리는 일은 한 사람을 부르시는 데서 시작됩니다.','The way home was lost.','People distrusted God and turned away. Sin and death entered, and relationships broke. Yet God promised a rescuer who would defeat evil.','Restoring this broken world would begin with the call of one person.'],
    ['patriarch','한 사람에게, 온 세상의 약속을.','하나님은 아브라함을 부르시고, 그의 후손을 통해 모든 민족에게 복을 주겠다고 약속하셨습니다. 작은 가족의 이야기가 온 세상을 향해 열립니다.','그 가족은 큰 민족이 되지만, 애굽에서 노예가 됩니다.','One family. A promise for everyone.','God called Abraham and promised to bless all nations through his descendants. The story of one small family opened toward the whole world.','That family grew into a nation—but became enslaved in Egypt.'],
    ['exodus','막힌 곳에, 길이 열리다.','하나님은 모세를 보내 이스라엘을 노예 생활에서 구하셨습니다. 바다를 지나 자유를 얻은 백성에게, 하나님과 함께 살아갈 길을 가르치셨습니다.','노예의 땅에서는 나왔습니다. 그러나 마음속의 죄는 남아 있었습니다.','A way where there was no way.','God sent Moses to rescue Israel from slavery. Beyond the sea, God taught his freed people how to live with him.','They had left the land of slavery. But sin still held their hearts.'],
    ['patriarch','구출. 망각. 그리고 또 구출.','약속의 땅에 들어간 백성은 하나님을 잊고 무너졌습니다. 고통 속에 부르짖으면 하나님이 구해 주셨지만, 같은 일이 반복되었습니다.','백성은 이 악순환을 끝내 줄 왕을 원했습니다.','Rescued. Forgetful. Rescued again.','In the promised land, the people forgot God and fell into trouble. When they cried out, God sent deliverers. Yet the same cycle kept returning.','The people wanted a king who could end the cycle.'],
    ['kingdom','왕관보다 오래갈 약속.','다윗이 왕이 되고 예루살렘에 나라가 세워졌습니다. 하나님은 다윗의 후손을 통해 영원한 나라를 세우겠다고 약속하셨습니다.','하지만 사람의 왕도, 화려한 성전도 백성의 마음을 바꾸지는 못했습니다.','A promise beyond the crown.','David became king, and Jerusalem became the heart of the kingdom. God promised that a descendant of David would reign over an everlasting kingdom.','But human kings and a magnificent temple could not change the people’s hearts.'],
    ['kingdom','나라가 갈라지고, 마음도 멀어지다.','나라는 둘로 갈라졌습니다. 왕과 백성은 우상을 따르고 약한 이들을 짓밟았습니다. 선지자들이 돌아오라고 외쳤지만, 그들은 듣지 않았습니다.','외면한 경고는 마침내 현실이 됩니다.','A divided kingdom. Divided hearts.','The kingdom split in two. Kings and people turned to idols and oppressed the vulnerable. Prophets called them back to God, but they would not listen.','The warnings they ignored finally came true.'],
    ['exile','모든 것을 잃은 자리에서.','나라는 무너지고 백성은 포로로 끌려갔습니다. 그러나 하나님은 그들을 버리지 않으셨습니다. 새 언약과 새 마음을 주겠다는 약속이 절망 속에 남았습니다.','세월이 흘러, 고향으로 돌아갈 문이 열립니다.','When everything was lost.','The kingdoms fell, and the people were taken into exile. Yet God did not abandon them. In their despair, he promised a new covenant and new hearts.','In time, a door opened for them to return home.'],
    ['kingdom','돌아왔지만, 아직 아니었다.','백성은 예루살렘으로 돌아와 성전과 성벽을 다시 세웠습니다. 하지만 모든 것이 회복된 것은 아니었습니다. 약속된 왕은 아직 오지 않았습니다.','그들은 기다립니다. 한 세대가 지나고, 또 한 세대가 지나도록.','Home again. But not yet whole.','The people returned to Jerusalem and rebuilt the temple and walls. But restoration was not complete. The promised king had not yet come.','They waited. One generation passed, and then another.'],
    ['bethlehem','약 400년.','구약의 마지막 선지자들 이후, 신약의 이야기까지 긴 시간이 흐릅니다. 제국은 바뀌고 백성은 기다렸습니다. 기독교 전통에서 ‘침묵기’라 부르는 이 시간에도 약속은 잊히지 않았습니다.','그리고, 작은 마을에 한 아기가 태어납니다.','About 400 years.','Between the last Old Testament prophets and the New Testament story, a long wait unfolded. Empires changed. The people waited. Christians often call this the “silent years”—but the promise was not forgotten.','Then, in a small town, a child was born.'],
    ['bethlehem','약속이, 사람이 되어 오다.','예수님은 권력의 중심이 아닌 낮은 자리로 오셨습니다. 아픈 사람을 고치고 죄인을 부르시며 하나님 나라를 전하셨습니다. 기다리던 구원은 바로 이분 안에 있었습니다.','그런데 구원으로 가는 길은 왕좌가 아니라 십자가로 향했습니다.','The promise became a person.','Jesus came, not to the center of power, but to a humble place. He healed the sick, welcomed sinners, and announced God’s kingdom. The long-awaited rescue had arrived in him.','But the road to rescue led not to a throne, but to a cross.'],
    ['church','이제, 세상 끝을 향해.','부활하신 예수님은 제자들을 보내셨습니다. 성령께서 오시고, 복음은 도시와 바다와 민족의 경계를 넘었습니다. 교회는 이 소식을 전하며 그분의 다시 오심을 기다립니다.','시작된 회복은 언젠가 온 세상을 새롭게 할 것입니다.','Now, to the ends of the earth.','The risen Jesus sent his followers into the world. The Holy Spirit came, and the good news crossed cities, seas, and nations. The church shares that news while awaiting his return.','The restoration already begun will one day make the whole world new.'],
    ['restoration','다시는, 헤어지지 않는다.','성경은 죽음과 눈물과 악이 끝나는 새 창조를 바라봅니다. 하나님이 사람들과 함께하십니다. 동산에서 시작된 이야기는, 온전히 회복된 하나님과의 관계로 완성됩니다.','잃어버린 집. 놓지 않은 약속. 다시 열린 길.','Never separated again.','The Bible looks ahead to a new creation, where death, tears, and evil end. God lives with his people. The story that began in a garden reaches its fulfillment in a relationship fully restored.','A home lost. A promise kept. A way opened again.']
  ];
  const extra = {
    ko:[['cross','사랑은, 여기까지 왔다.','예수님은 우리의 죄를 짊어지고 십자가에서 죽으셨습니다. 성경은 이 죽음을 패배가 아니라, 죄인을 하나님께 되돌리는 사랑의 구원으로 전합니다.','모든 것이 끝난 것처럼 보였습니다.'],['resurrection','그러나, 죽음이 끝은 아니었다.','예수님은 죽음을 이기고 부활하셨습니다. 무덤은 비었고, 제자들은 부활하신 주님을 만났습니다. 죄와 죽음보다 강한 새 생명이 시작되었습니다.','이 소식은 더 이상 한 민족 안에 머물 수 없었습니다.']],
    en:[['cross','Love went this far.','Jesus bore our sin and died on the cross. The Bible presents this death not as defeat, but as God’s loving rescue, bringing sinners back to him.','It looked as though everything was over.'],['resurrection','But death was not the end.','Jesus defeated death and rose again. The tomb was empty, and his followers met their risen Lord. A new life stronger than sin and death had begun.','This news could no longer stay within one nation.']]
  };
  const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function image(name,eager=false){const root=global.__CINEMA_ROOT__||'/';return `<picture class="film-art" aria-hidden="true"><source media="(max-width: 600px)" srcset="${root}v2/art/${name}-640.webp"><img src="${root}v2/art/${name}-960.webp" width="1024" height="1536" alt="" loading="${eager?'eager':'lazy'}" decoding="async" ${eager?'fetchpriority="high"':''}></picture>`;}
  function stage(data,label,id='',eager=false){return `<div class="film-stage film-${data[0]}" ${id?`id="${id}"`:''}>${image(data[0],eager)}<div class="film-atmosphere" aria-hidden="true"></div><div class="film-copy"><p class="film-label">${esc(label)}</p><h2>${esc(data[1])}</h2><p class="film-narrative">${esc(data[2])}</p></div></div><p class="film-bridge"><span aria-hidden="true"></span>${esc(data[3])}<span aria-hidden="true">↓</span></p>`;}
  function mount(pack,lang){
    if(!['ko','en'].includes(lang))return;
    const en=lang==='en', html=document.documentElement;
    html.classList.add('cinema');
    const hero=document.querySelector('.hero');
    hero.innerHTML=`${image('creation',true)}<div class="film-atmosphere" aria-hidden="true"></div><div class="film-hero-copy"><p class="film-brand">ONE SCROLL BIBLE <span>THE CINEMATIC EDITION</span></p><p class="film-label">${en?'66 BOOKS. ONE STORY.':'66권의 성경, 하나의 이야기.'}</p><h1>${en?'A way<br>back home.':'다시,<br>집으로 가는 길.'}</h1><p class="film-intro">${en?'A world made good. A love that would not let go.<br>The whole Bible, in one unforgettable journey.':'아름답게 시작된 세상. 끝내 포기하지 않은 사랑.<br>성경 전체를 하나의 이야기로 만나보세요.'}</p><a class="film-start" href="#s1">${en?'Begin the story':'이야기 속으로'} <span>↓</span></a><p class="film-time">${en?'About 5 minutes · 13 chapters · No Bible knowledge needed':'약 5분 · 13장면 · 성경을 몰라도 괜찮아요'}</p><div class="film-options"><button id="heroLangBtn" type="button">${en?'English · 210+ languages':'한국어 · 210개 이상의 언어'}</button><button id="filmReadMode" type="button" aria-pressed="false">${en?'Reading mode':'읽기 모드'}</button></div></div>`;
    const thread=document.querySelector('.thread');
    thread.innerHTML=`<div class="film-prologue"><p class="film-label">${en?'THE THREAD TO FOLLOW':'이 세 단어를 기억하세요'}</p><div class="film-acts"><span>${en?'Promise':'약속'}</span><i>→</i><span>${en?'Waiting':'기다림'}</span><i>→</i><span>${en?'Fulfillment':'성취'}</span></div><p>${en?'People break the relationship. God keeps his promise.<br>Watch how every chapter leads toward Jesus.':'사람은 관계를 깨뜨리지만, 하나님은 약속을 놓지 않으십니다.<br>이야기가 어떻게 예수님을 향해 가는지 따라가 보세요.'}</p><details class="film-chapters"><summary>${en?'Choose a chapter':'장면 바로가기'} <span>＋</span></summary><ol>${pack.epochs.map((e,i)=>`<li><a href="#s${i+1}"><span>${String(i+1).padStart(2,'0')}</span>${esc(e.title)}</a></li>`).join('')}</ol></details></div>`;
    document.querySelectorAll('#epochs > .epoch').forEach((section,i)=>{
      const drawer=section.querySelector('.scene-drawer');
      const row=rows[i], offset=en?4:1;
      const data=[row[0],row[offset],row[offset+1],row[offset+2]];
      const act=i<3?(en?'PROMISE':'약속'):i<10?(en?'WAITING':'기다림'):(en?'FULFILLMENT':'성취');
      section.innerHTML=stage(data,`${String(i+1).padStart(2,'0')} / 13 · ${act} · ${pack.epochs[i].title}`);
      if(i===10) extra[lang].forEach((d,j)=>section.insertAdjacentHTML('beforeend',stage(d,`${en?'JESUS':'예수님'} · ${j===0?(en?'THE CROSS':'십자가'):(en?'RESURRECTION':'부활')}`,j===0?'the-cross':'the-resurrection')));
      if(drawer){const wrap=document.createElement('div');wrap.className='film-details';wrap.append(drawer);section.append(wrap);}
      section.insertAdjacentHTML('beforeend',`<div class="film-scene-footer"><span>${act}</span><div class="film-thread-line" aria-hidden="true"><i style="width:${(i+1)/13*100}%"></i></div><button class="ep-share" type="button" data-sc="${i+1}" aria-label="${en?'Share this chapter':'이 장면 공유'}">${en?'Share':'공유'} ↗</button></div>`);
    });
    const ending=document.getElementById('storyComplete');
    const recap=en?['God made a good world for life with him.','People turned away, but God promised a rescue.','Through Israel, the world waited for the promised king.','Jesus died and rose to bring us back to God.','His good news goes to all nations, until all things are new.']:['하나님은 함께 살 아름다운 세상을 만드셨습니다.','사람은 등을 돌렸지만, 하나님은 구원을 약속하셨습니다.','이스라엘의 역사는 약속된 왕을 기다리는 이야기입니다.','예수님은 우리를 하나님께 되돌리려고 죽고 부활하셨습니다.','이 소식은 모든 민족에게 전해지고, 마침내 만물이 새로워집니다.'];
    const memory=document.createElement('div');memory.className='film-memory';memory.innerHTML=`<p class="film-label">${en?'YOU KNOW THE STORY NOW':'이제, 당신도 이 이야기를 압니다'}</p><h2>${en?'One story.<br>Yours to tell.':'한 편의 이야기.<br>이제 누군가에게 들려주세요.'}</h2><ol>${recap.map((s,i)=>`<li><a href="#s${[1,2,3,11,13][i]}">${image(['creation','fall','patriarch','resurrection','restoration'][i])}<span>${esc(s)}</span></a></li>`).join('')}</ol><p class="film-art-note">${en?'The artwork is an imaginative interpretation, not a historical reconstruction. This is a Christian, evangelical, redemptive-historical reading of the Bible; other traditions may understand passages differently.':'그림은 이야기를 돕는 예술적 상상이며 역사적 복원도가 아닙니다. 이 사이트는 복음주의·구속사적 기독교 관점으로 성경을 소개합니다. 다른 전통은 일부 본문을 다르게 이해할 수 있습니다.'}</p>`;
    ending.prepend(memory);
    document.getElementById('filmReadMode').addEventListener('click',function(){const on=html.classList.toggle('film-reading');this.setAttribute('aria-pressed',String(on));this.textContent=en?(on?'Cinematic mode':'Reading mode'):(on?'영화 모드':'읽기 모드');});
    const stages=[...document.querySelectorAll('.film-stage,.cinema .hero')];
    const reduced=matchMedia('(prefers-reduced-motion: reduce)');
    let queued=false;
    function paint(){queued=false;if(reduced.matches||html.classList.contains('film-reading'))return;const vh=innerHeight;stages.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>vh)return;const t=Math.max(-1,Math.min(1,(vh/2-r.top-r.height/2)/(vh+r.height)));el.style.setProperty('--film-drift',`${t*32}px`);});}
    window.addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(paint);}},{passive:true});
    const obs=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('film-visible',e.isIntersecting)),{rootMargin:'100px'});stages.forEach(el=>obs.observe(el));paint();
  }
  global.OSBCinema={mount,rows,extra};
})(typeof window!=='undefined'?window:globalThis);
